cloud:
  aws:
    credentials:

    region:
      static: us-west-1

    stack:
      auto: false

application:
  bucket:
    name: groceryproductimages

#spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold:2MB
#      max-file-size:5MB
#      max-request-size:10MB
#


server:
  port: 9090

